- name: Compiling translations
  command: ./bin/tr_compile.py
  become_user: titan
  args:
    chdir: /home/titan/Titan/webapp

- name: Restart webserver
  systemd: name=titanembeds state=restarted enabled=yes

- name: Restart nginx
  service: name=nginx enabled=yes state=restarted
