- hosts: titanembeds
  remote_user: root
  roles:
    - role: ../../roles/ansible-letsencrypt
      tags: ['always']
      letsencrypt_webroot_path: /var/www/wellknown
      letsencrypt_email: change_me
      letsencrypt_cert_domains:
        - change_me
      letsencrypt_renewal_command_args: '--renew-hook "service nginx restart"'
    - role: ../../roles/unattended-upgrades
      tags: ['always']
    - role: ../../roles/web
      tags: ['web']
    - role: ../../roles/bot
      tags: ['bot']
