- hosts: titanembeds
  remote_user: root
  roles:
    - role: ../../roles/ansible-letsencrypt
      tags: ['always']
      letsencrypt_webroot_path: /var/www/wellknown
      letsencrypt_email: RainbowDash@equestria.net
      letsencrypt_cert_domains:
        - titanembeds.com
    - role: ../../roles/unattended-upgrades
      tags: ['always']
    - role: ../../roles/web
      tags: ['web']
    - role: ../../roles/bot
      tags: ['bot']
